### PR TITLE
Snmp measurement

### PR DESCRIPTION
**Pull request by Kri-7-q**
Measurement works but has no result pages.

### CODE REVIEW

**Comment by MKV21** [comment]
Android and Windows do not like this, see https://mplane.informatik.hs-augsburg.de/viewLog.html?buildId=8306&buildTypeId=MPlane_ClientMasterDebugBundledAndroidArmv7&tab=buildLog and https://mplane.informatik.hs-augsburg.de/viewLog.html?buildId=8304&buildTypeId=MPlane_ClientDebugWindows&tab=buildLog

**Comment by MKV21** [comment]
Can you try to include the net-snmp as a git submodule? (git clone git://git.code.sf.net/p/net-snmp/code net-snmp-code)

**Comment by Kri-7-q** [comment]
Android build problem fixed.
May it build on Windows to.
But I still get the error message: Project ERROR: Unknown module(s) in QT: systeminfo

**Comment by monstermunchkin** [comment]
Good work @Kri-7-q. Unfortunately the Windows build is broken due to issues inside the net-snmp project itself. Since we do not know how to resolve these problems at the moment, I will be closing this pull request for now.

**Pull request closed without merging**
